# version: '3.8'
# services:
#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: senha
#       POSTGRES_DB: poncetech
#     ports:
#       - '5432:5432'
#   app:
#     build: .
#     command: npm run start:dev
#     ports:
#       - '3000:3000'
#     depends_on:
#       - db